project:
  name: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: '@project.description@'
    version: '@project.version@'



#spring.banner.charset=UTF-8
#spring.banner.location=classpath:banner.txt

spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLE}
  banner:

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''




#Logging
logging:
  level:
    br.senac.go: debug
    org.springframework.web: info

resource:
  cliente-post: Método responsável por criar uma nova pessoa.
  cliente-put: Método responsável por atualizar todo os dados de uma pessoa.
  cliente-patch: Método responsável por atualizar parte de um objeto pessoa.
  cliente-delete: Método responsável por deletetar o registro pessoa.
  cliente-delete-by-id: Método responsável por deletar um registro por identificador.
